// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOKjYDWaXV_4vjL55GQ4J_RUajNACpRcs',
    appId: '1:662337353035:web:462f5fb9ffc6b310f024ce',
    messagingSenderId: '662337353035',
    projectId: 'toeicapp-6661d',
    authDomain: 'toeicapp-6661d.firebaseapp.com',
    storageBucket: 'toeicapp-6661d.firebasestorage.app',
    measurementId: 'G-JWLDNRJS66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCReGMb0swwY3o2IsSauX1ALS_D2_QQbSY',
    appId: '1:662337353035:android:4d0986547afbd913f024ce',
    messagingSenderId: '662337353035',
    projectId: 'toeicapp-6661d',
    storageBucket: 'toeicapp-6661d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOKjYDWaXV_4vjL55GQ4J_RUajNACpRcs',
    appId: '1:662337353035:web:9999277f347f5586f024ce',
    messagingSenderId: '662337353035',
    projectId: 'toeicapp-6661d',
    authDomain: 'toeicapp-6661d.firebaseapp.com',
    storageBucket: 'toeicapp-6661d.firebasestorage.app',
    measurementId: 'G-VQY1L0JF2J',
  );
}
